name: Publish Extension

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install
        
      - name: Run linting
        run: pnpm run lint
        
      - name: Run type checking
        run: pnpm run typecheck
        
      - name: Build Extension
        run: pnpm run build
        
      - name: Install vsce
        run: pnpm add -g @vscode/vsce
        
      - name: Package Extension
        run: vsce package
        
      - name: Publish to Visual Studio Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
